import {useEffect,useState} from 'react';
import AtlasHeader from './atlas-header';
import {verifiedForms} from './verified-forms';
import {DRAFT_KEY,emptyDraft,parseDraft,moveForm,type QuestionnaireDraft} from './questionnaire-draft';
const available=new Set(verifiedForms.map(f=>f.id));
export default function QuestionnaireBuilder(){
 const [draft,setDraft]=useState<QuestionnaireDraft>(emptyDraft),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem(DRAFT_KEY);if(raw)setDraft(parseDraft(JSON.parse(raw),available));}catch{setMessage('浏览器未能读取已有方案。本页仍可选择量表，请及时下载备份。');}setLoaded(true);},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify(draft));}catch{setMessage('浏览器无法保存方案，请下载备份后再离开。');}},[draft,loaded]);
 const selected=draft.formIds.map(id=>verifiedForms.find(f=>f.id===id)!);
 const matches=verifiedForms.filter(f=>(f.label+' '+f.language).toLowerCase().includes(query.trim().toLowerCase()));
 function backup(){const blob=new Blob([JSON.stringify(draft,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='量表选择方案.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('已生成方案备份。它记录选表和顺序，尚不是可发放的正式问卷。');}
 async function restore(file:File|undefined){if(!file)return;if(file.size>100000){setMessage('备份文件过大，请选择本页导出的方案文件。');return;}try{const value=JSON.parse(await file.text());if(value.schema!==1||!Array.isArray(value.formIds)||value.formIds.some((id:unknown)=>typeof id!=='string'||!available.has(id)))throw Error('unknown form');setDraft(parseDraft(value,available));setMessage('已恢复方案。');}catch{setMessage('文件格式不匹配或含已不可用表单，未改变当前方案。');}}
 return <div className="atlas"><AtlasHeader active="builder" summary="选择具体译本，保存调查方案"/><main className="atlas-body builder-page"><header><h1>我的问卷方案</h1><p>先选择适合的具体版本和语言，再安排顺序。方案只保存在当前浏览器；下载备份后可在其他设备恢复。</p><p className="intro-evidence-note">目前开放已整理题文的表单供选表规划。正式问卷与使用说明导出仍在建设，选入方案不代表已完成目标人群验证。</p></header>
 <section className="builder-card" aria-labelledby="export-example"><h2 id="export-example">问卷与使用说明示例</h2><p>已完成 DASS-21 Taouk Moussa 等繁体中文译本的配套文件示例，题目、计分题号、来源链接及分页已检查。以下是固定示例，不会随当前选表改变；任意组合自动导出仍在建设。</p><p>问卷保留原题文；使用说明列出计分、缺失值处理及证据边界。该译本与具体中文验证研究的逐字匹配仍待完成，正式调查前请核对适用人群和使用条件。</p><div className="builder-actions"><a href="./examples/dass21-questionnaire.docx" download>问卷 Word</a><a href="./examples/dass21-questionnaire.pdf" download>问卷 PDF</a><a href="./examples/dass21-instructions.docx" download>使用说明 Word</a><a href="./examples/dass21-instructions.pdf" download>使用说明 PDF</a></div></section>
 <div className="builder-layout"><section className="builder-card"><h2>可选表单</h2><label htmlFor="form-filter">搜索名称或语言</label><input id="form-filter" value={query} onChange={e=>setQuery(e.target.value)} placeholder="例如 PHQ-9、简体中文"/>{!matches.length&&<p>暂无匹配表单。其余量表的题文正在核对。</p>}
 {matches.map(f=><article className="builder-form" key={f.id}><h3>{f.label}</h3><p>{f.itemCount}题 · {f.language}</p><p>{f.translationEvidence}</p><a href={f.sourceUrl} target="_blank" rel="noreferrer">核对原件 ↗</a><button type="button" disabled={!loaded||draft.formIds.includes(f.id)} onClick={()=>setDraft(x=>({...x,formIds:[...x.formIds,f.id]}))}>{draft.formIds.includes(f.id)?'已选入':'加入方案'}</button></article>)}</section>
 <section className="builder-card builder-selected"><h2>已选 {selected.length} 份 · {selected.reduce((sum,f)=>sum+f.itemCount,0)} 道计分题</h2><label htmlFor="draft-title">方案名称</label><input id="draft-title" value={draft.title} maxLength={160} disabled={!loaded} onChange={e=>setDraft(x=>({...x,title:e.target.value}))}/>{!selected.length&&<p>从可选表单中加入量表。每份表单保留原题文，不能在这里改写正式题目。</p>}
 <ol className="builder-order">{selected.map((f,i)=><li key={f.id}><h3>{f.label}</h3>{selected.some(other=>other.id!==f.id&&other.versionId===f.versionId)&&<p className="intro-evidence-note">同一量表选择了多个译本，请确认是否计划重复施测。</p>}<p>{f.itemCount}道计分题{f.supplementaryItems?.length?`，另有${f.supplementaryItems.length}道不计分附加题`:''}</p><div className="builder-actions"><button disabled={i===0} onClick={()=>setDraft(x=>moveForm(x,f.id,-1))} aria-label={'上移'+f.label}>上移</button><button disabled={i===selected.length-1} onClick={()=>setDraft(x=>moveForm(x,f.id,1))} aria-label={'下移'+f.label}>下移</button><button onClick={()=>setDraft(x=>({...x,formIds:x.formIds.filter(id=>id!==f.id)}))} aria-label={'移除'+f.label}>移除</button></div></li>)}</ol>
 <div className="builder-actions"><button disabled={!loaded||!selected.length} onClick={backup}>下载方案备份</button><label className="builder-restore">恢复备份<input type="file" accept=".json,application/json" onChange={e=>{void restore(e.target.files?.[0]);e.target.value='';}}/></label></div><p role="status" aria-live="polite">{message}</p><p>备份仅含方案名称、表单标识及顺序，不含受访者作答。清除浏览器数据会删除本地方案。</p></section></div></main></div>;
}
