import type {createQuestionnairePackage} from './questionnaire-package';
type Package=ReturnType<typeof createQuestionnairePackage>;
const escape=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const p=(text:string)=>`<p>${escape(text)}</p>`;
const link=(url:string,label:string)=>/^https:\/\//.test(url)?`<a href="${escape(url)}">${escape(label)}</a>`:escape(label);
export function renderQuestionnairePrint(data:Package,kind:'questionnaire'|'instructions'){
 if(!data.ready)throw new Error('所选表单仍有未完成的核验，暂不能生成正式文件。');
 const content=kind==='questionnaire'?data.questionnaire.map((f,index)=>`<section><h2>${index+1} ${escape(f.label)}</h2>${p(f.instructions)}<table class="response-table"><thead><tr><th>题目</th>${f.options.map(o=>`<th>${escape(o.label)}<br>${escape(o.responseCode)}</th>`).join('')}</tr></thead><tbody>${f.items.map(i=>`<tr><td>${i.number}. ${escape(i.text)}</td>${f.options.map(o=>`<td class="response">${escape(o.responseCode)}</td>`).join('')}</tr>`).join('')}</tbody></table>${f.supplementaryItems.map(i=>`<div class="question">${p(i.text)}${i.options.map(o=>p('□ '+o)).join('')}</div>`).join('')}<div class="source">${p(f.usage)}${link(f.sourceUrl,'问卷来源原件')}</div></section>`).join(''):
 data.instructions.map((f,index)=>`<section><h2>${index+1} ${escape(f.label)}</h2><h3>用途与适用边界</h3>${f.profile?.definition.map(x=>p(x.text)+link(x.source,x.label)).join('')??p('版本简介尚未提供。')}<h3>施测与计分</h3>${f.profile?.scoring.map(x=>p(x.text)+link(x.source,x.label)).join('')??''}${f.scoringNote?p(f.scoringNote):''}${p('各题回答与计分：'+f.options.map(o=>`${o.label}（回答编号${o.printedCode??o.value}，计${o.value}分）`).join('；'))}${Object.entries(f.dimensions).map(([name,items])=>p(`${({D:"抑郁",A:"焦虑",S:"压力"} as Record<string,string>)[name]??name}：题号${items.join('、')}。原始分范围${f.rawSubscaleRange.join('—')}；比较用乘数${f.comparisonMultiplier}。`)).join('')}<h3>解释限制与中文证据</h3>${p(f.translationEvidence)}${f.profile?.limits.map(x=>p(x.text)+link(x.source,x.label)).join('')??''}<h3>使用与来源</h3>${p(f.usage)}${p('题文核对日期：'+f.verifiedAt)}<ul><li>${link(f.sourceUrl,'官方题本')}</li><li>${link(f.scoringSource,'官方评分资料')}</li><li>${link(f.rightsSource,'授权说明')}</li></ul><p class="source">原件校验标识 SHA256 ${escape(f.sourceSha256)}</p></section>`).join('');
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>${escape(data.title)} ${kind==='questionnaire'?'问卷':'使用说明'}</title><style>@page{size:Letter;margin:18mm}*{box-sizing:border-box}body{font:12pt/1.6 'Microsoft YaHei',Arial,sans-serif;color:#111;max-width:180mm;margin:0 auto}h1{font-size:22pt}h2{font-size:16pt;break-after:avoid}h3{font-size:13pt;break-after:avoid}p{margin:7pt 0}section+section{break-before:page}a{color:#17486b;overflow-wrap:anywhere;font-size:10pt}.response-table{width:100%;border-collapse:collapse;table-layout:fixed;margin:12pt 0}.response-table thead{display:table-header-group}.response-table th{font-size:10pt;font-weight:normal;padding:8pt 4pt;border-bottom:1px solid #aaa}.response-table th:first-child{width:56%;text-align:left}.response-table td{padding:9pt 4pt;border-bottom:1px solid #ddd;vertical-align:middle}.response-table tr{break-inside:avoid}.response{text-align:center}.options{margin:12pt 0}.options p{margin:2pt 0}.questions{padding-left:24pt}.questions li,.question{break-inside:avoid;margin:0 0 13pt}.questions li p{margin-bottom:5pt}.answers{display:flex;gap:28pt}.source{font-size:9pt;overflow-wrap:anywhere;margin-top:16pt}.meta{font-size:10pt;color:#555}</style></head><body><h1>${escape(data.title)} ${kind==='questionnaire'?'问卷':'使用说明'}</h1><p class="meta">方案快照 ${escape(data.createdAt)}</p>${kind==='instructions'?p('本文件供研究者核对所选版本、施测、计分和使用条件。请与同一快照的问卷配套保存；量表结果不替代临床诊断。'):''}${content}</body></html>`;
}
