// Dependency is supplied by the caller so the same renderer works in browser and QA.
export function createQuestionnaireDocx(data,kind,d){
if(!data.ready)throw new Error('所选表单仍有未完成的核验，暂不能生成正式文件。');
if(!['questionnaire','instructions'].includes(kind))throw new Error('未知文件类型');
const {Document,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,BorderStyle,HeadingLevel,Packer,ExternalHyperlink}=d;
const text=(value,options={})=>new Paragraph({children:[new TextRun({text:value,...options})],spacing:{after:100}});
const heading=(value,level=HeadingLevel.HEADING_2)=>new Paragraph({text:value,heading:level,keepNext:true,spacing:{before:220,after:120}});
const link=(url,label)=>new Paragraph({children:[new ExternalHyperlink({link:url,children:[new TextRun({text:label,style:'Hyperlink'})]})],spacing:{after:100}});
const border={style:BorderStyle.SINGLE,size:4,color:'D9D9D9'};
const cell=(value,width,header=false)=>new TableCell({width:{size:width,type:WidthType.DXA},verticalAlign:'center',margins:{top:90,bottom:90,left:90,right:90},shading:header?{fill:'EAF1F6'}:undefined,borders:{top:border,bottom:border,left:border,right:border},children:[new Paragraph({alignment:width<1500?'center':'left',children:[new TextRun({text:String(value),size:22})]})]});

 const body=[heading(data.title+' '+(kind==='questionnaire'?'问卷':'使用说明'),HeadingLevel.TITLE),text('方案快照 '+data.createdAt,{size:20})];
 if(kind==='questionnaire')for(const q of data.questionnaire){body.push(heading(q.label),text(q.instructions));const widths=[5200,...q.options.map(()=>(9360-5200)/q.options.length)];body.push(new Table({width:{size:9360,type:WidthType.DXA},columnWidths:widths,rows:[new TableRow({tableHeader:true,children:[new TableCell({columnSpan:widths.length,width:{size:9360,type:WidthType.DXA},margins:{top:100,bottom:100,left:100,right:100},children:q.options.map(o=>new Paragraph({spacing:{line:240,after:50},children:[new TextRun({text:o.responseCode+' '+o.label,size:20})]}))})]}),new TableRow({tableHeader:true,children:[cell('题目',widths[0],true),...q.options.map((o,i)=>cell(o.responseCode,widths[i+1],true))]}),...q.items.map(i=>new TableRow({cantSplit:true,children:[cell(i.number+'. '+i.text,widths[0]),...q.options.map((o,j)=>cell(o.responseCode,widths[j+1]))]}))]}),...q.supplementaryItems.flatMap(item=>[text(item.text),...item.options.map(option=>text('□ '+option))]),text(q.usage,{size:20}),link(q.sourceUrl,'问卷来源原件'));}
 else for(const q of data.instructions){body.push(text('本文件供研究者核对版本、施测、计分和使用条件。请与同一快照的问卷配套保存。'),heading(q.label));for(const [title,paragraphs]of[['用途与适用边界',q.profile?.definition??[]],['施测与计分',q.profile?.scoring??[]],['解释限制',q.profile?.limits??[]]]){body.push(heading(title));for(const p of paragraphs)body.push(text(p.text),link(p.source,p.label));}if(q.scoringNote)body.push(text(q.scoringNote));body.push(heading('题号与分数'),text(q.options.map(o=>`${o.label}：回答编号${o.printedCode??o.value}，计${o.value}分`).join('；')));for(const[name,ids]of Object.entries(q.dimensions))body.push(text(`${({D:'抑郁',A:'焦虑',S:'压力'})[name]??name}：题号${ids.join('、')}；原始分范围${q.rawSubscaleRange.join('—')}；比较用乘数${q.comparisonMultiplier}。`));body.push(heading('中文证据与使用条件'),text(q.translationEvidence),text(q.usage),link(q.sourceUrl,'官方题本'),link(q.scoringSource,'官方评分资料'),link(q.rightsSource,'授权说明'),text('题文核对日期 '+q.verifiedAt,{size:20}));}
 const doc=new Document({creator:'公共卫生量表库',title:data.title,styles:{default:{document:{run:{font:'Microsoft YaHei',size:24,color:'000000'},paragraph:{spacing:{line:320}}}},paragraphStyles:[{id:'Title',name:'Title',basedOn:'Normal',run:{size:40,bold:true,color:'000000'}},{id:'Heading2',name:'Heading 2',basedOn:'Normal',run:{size:28,bold:true,color:'000000'}}]},sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1080,bottom:1080,left:1440,right:1440}}},children:body}]});
return doc;
}

